import {describe,expect,it} from "vitest";
import type {DailyFocus,Task,TaskEvent} from "@/types";
import {groupOpenItems,monthlyTaskStats,tasksForDate,weeklyTaskStats} from "./index";

const base=(patch:Partial<Task>):Task=>({id:"t1",title:"一件事",status:"open",domain:"study",contextPoints:[],plannedDate:"2026-07-08",createdAt:"2026-06-01T00:00:00.000Z",updatedAt:"2026-07-08T00:00:00.000Z",...patch});
const event=(patch:Partial<TaskEvent>):TaskEvent=>({id:"e1",taskId:"t1",type:"created",occurredAt:"2026-07-06T10:00:00.000Z",localDate:"2026-07-06",timezone:"Asia/Shanghai",...patch});

describe("task statistics",()=>{
  it("keeps reschedules after completion and uses unique completions",()=>{const tasks=[base({status:"done"})];const events=[event({type:"rescheduled",fromDate:"2026-07-08",toDate:"2026-07-15"}),event({id:"e2",type:"completed",localDate:"2026-07-08"}),event({id:"e3",type:"completed",localDate:"2026-07-09"})];expect(weeklyTaskStats(tasks,events,[],"2026-07-06","2026-07-12")).toMatchObject({done:1,rescheduled:1,dropped:0});expect(monthlyTaskStats(tasks,events,2026,6)).toMatchObject({done:1,open:0,rescheduled:1})});
  it("uses localDate instead of slicing UTC",()=>{const events=[event({type:"completed",occurredAt:"2026-07-05T16:30:00.000Z",localDate:"2026-07-06"})];expect(weeklyTaskStats([base({status:"done"})],events,[],"2026-07-06","2026-07-12").done).toBe(1)});
  it("counts focus completed on its assigned date",()=>{const focus:DailyFocus[]=[{date:"2026-07-06",taskId:"t1",assignedAt:""}];const events=[event({type:"completed",localDate:"2026-07-06"})];expect(weeklyTaskStats([base({status:"open"})],events,focus,"2026-07-06","2026-07-12").focus).toEqual({assigned:1,completed:1})});
  it("does not backfill focus completion from a later date",()=>{const focus:DailyFocus[]=[{date:"2026-07-06",taskId:"t1",assignedAt:""}];const events=[event({type:"completed",localDate:"2026-07-10"})];expect(weeklyTaskStats([base({status:"done"})],events,focus,"2026-07-06","2026-07-12").focus).toEqual({assigned:1,completed:0})});
});
describe("open item groups",()=>{it("places open tasks in exactly one time group",()=>{const before=base({id:"before",plannedDate:"2026-07-10"});const today=base({id:"today",plannedDate:"2026-07-11"});const future=base({id:"future",plannedDate:"2026-07-12"});const someday=base({id:"someday",plannedDate:undefined});const dropped=base({id:"drop",status:"dropped"});const groups=groupOpenItems([before,today,future,someday,dropped],"2026-07-11");expect(groups.before.map(task=>task.id)).toEqual(["before"]);expect(groups.today.map(task=>task.id)).toEqual(["today"]);expect(groups.after.map(task=>task.id)).toEqual(["future","someday"]);expect(groups.dropped.map(task=>task.id)).toEqual(["drop"]);expect(new Set([...groups.before,...groups.today,...groups.after].map(task=>task.id)).size).toBe(4)})});
describe("calendar history",()=>{it("returns a task on both sides of a reschedule",()=>{const task=base({plannedDate:"2026-07-15"});const events=[event({type:"rescheduled",fromDate:"2026-07-08",toDate:"2026-07-15"})];expect(tasksForDate([task],events,"2026-07-08").map(value=>value.id)).toEqual(["t1"]);expect(tasksForDate([task],events,"2026-07-15").map(value=>value.id)).toEqual(["t1"])})});
