"use client";
import {useEffect,useState} from "react";
import {Button} from "@/components/ui/Button";
import {Card} from "@/components/ui/Card";
import {getAutostartEnabled,getShortcutSettings,isDesktopRuntime,setAutostartEnabled,updateShortcutSettings,type ShortcutSettings} from "@/lib/desktop/tauri-client";

const defaults:ShortcutSettings={todoPanel:"Ctrl+Shift+O",sparkCapture:"Ctrl+Shift+Space",issues:[]};
export function DesktopSettings(){const [desktop,setDesktop]=useState(false);const [shortcuts,setShortcuts]=useState(defaults);const [autostart,setAutostart]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
  useEffect(()=>{Promise.resolve().then(()=>{const available=isDesktopRuntime();setDesktop(available);if(!available)return Promise.resolve();return Promise.all([getShortcutSettings(),getAutostartEnabled()]).then(([next,enabled])=>{setShortcuts(next);setAutostart(enabled)}).catch(error=>setMessage(String(error)))})},[]);
  async function save(event:React.FormEvent){event.preventDefault();setBusy(true);setMessage("");try{const next=await updateShortcutSettings(shortcuts);setShortcuts(next);setMessage(next.issues.length?"设置已保存，但部分快捷键注册失败。":"桌面快捷键已更新。")}catch(error){setMessage(String(error))}finally{setBusy(false)}}
  async function changeAutostart(enabled:boolean){setBusy(true);try{setAutostart(await setAutostartEnabled(enabled));setMessage(enabled?"已开启开机启动。":"已关闭开机启动。")}catch(error){setMessage(String(error))}finally{setBusy(false)}}
  return <Card className="setting-card desktop-settings-card"><span className="tiny-label">Desktop</span><h2>桌面行为</h2><p className="muted">主窗口关闭后隐藏到托盘；托盘“退出”才会结束应用。快捷键冲突只会停用对应快捷键，不影响应用启动。</p>{!desktop?<p className="provider-warning">这些设置只在 Open Ends 桌面应用中可用。</p>:<><label className="desktop-toggle"><input type="checkbox" checked={autostart} disabled={busy} onChange={event=>changeAutostart(event.target.checked)}/><span>登录 Windows 后自动启动 Open Ends</span></label><form className="shortcut-form" onSubmit={save}><label className="label">显示 / 隐藏今日悬浮窗<input className="field" value={shortcuts.todoPanel} onChange={event=>setShortcuts(current=>({...current,todoPanel:event.target.value}))}/></label><label className="label">打开闪念窗口<input className="field" value={shortcuts.sparkCapture} onChange={event=>setShortcuts(current=>({...current,sparkCapture:event.target.value}))}/></label><Button disabled={busy}>保存快捷键</Button></form>{shortcuts.issues.map(issue=><p className="provider-warning" key={issue}>{issue}</p>)}</>}{message&&<p className="backup-message muted">{message}</p>}</Card>}
