import {describe,expect,it} from "vitest";
import {createEmptyStore} from "@/lib/storage/migrate";
import type {ReadingEvent,Task,TaskEvent} from "@/types";
import {buildMonthlySnapshot,buildWeeklySnapshot,buildYearlySnapshot,createSnapshotRevision} from "./snapshots";

const task:Task={id:"t",title:"完成基座",contextPoints:[],status:"done",domain:"project",plannedDate:"2026-12-31",createdAt:"2026-12-20T00:00:00Z",updatedAt:"2027-01-01T00:00:00Z",completedAt:"2027-01-01T00:00:00Z"};
const completed:TaskEvent={id:"e",taskId:"t",type:"completed",occurredAt:"2026-12-31T16:30:00Z",localDate:"2027-01-01",timezone:"Asia/Shanghai"};
describe("snapshot builders",()=>{
  it("is deterministic for the same facts regardless of input order",async()=>{const first=createEmptyStore();first.tasks=[task];first.taskEvents=[completed,{...completed,id:"r",type:"rescheduled",occurredAt:"2026-12-30T00:00:00Z",localDate:"2026-12-30"}];const second={...first,taskEvents:[...first.taskEvents].reverse()};const a=await buildWeeklySnapshot(first,"2026-12-28");const b=await buildWeeklySnapshot(second,"2026-12-28");expect(a.factsJson).toBe(b.factsJson);expect(a.sourceHash).toBe(b.sourceHash);expect(a.periodEnd).toBe("2027-01-03")});
  it("handles leap-year monthly and yearly boundaries",async()=>{const data=createEmptyStore();expect((await buildMonthlySnapshot(data,2024,1)).periodEnd).toBe("2024-02-29");expect((await buildYearlySnapshot(data,2024)).periodEnd).toBe("2024-12-31")});
  it("creates a new revision only when sourceHash changes",async()=>{const data=createEmptyStore();const draft=await buildWeeklySnapshot(data,"2026-08-17");const first=createSnapshotRevision(draft,[],"s1","2026-08-24T00:00:00Z");expect(first?.revision).toBe(1);expect(createSnapshotRevision(draft,[first!],"s2","2026-08-25T00:00:00Z")).toBeNull();const changed={...draft,sourceHash:"changed"};expect(createSnapshotRevision(changed,[first!],"s2","2026-08-25T00:00:00Z")).toMatchObject({revision:2,supersedesId:"s1"})});
  it("separates backfilled finishes from lifecycle finishes",async()=>{const data=createEmptyStore();data.readingItems=[{id:"book",title:"一本书",type:"book",status:"finished",createdAt:"2026-08-01T00:00:00Z",updatedAt:"2026-08-30T00:00:00Z"}];const added:ReadingEvent={id:"added",readingItemId:"book",type:"added",occurredAt:"2026-08-01T00:00:00Z",localDate:"2026-08-01",timezone:"Asia/Shanghai"};const finished:ReadingEvent={id:"finished",readingItemId:"book",type:"finished",occurredAt:"2026-08-30T00:00:00Z",localDate:"2026-08-30",timezone:"Asia/Shanghai"};data.readingEvents=[added,finished];const facts=JSON.parse((await buildWeeklySnapshot(data,"2026-08-24")).factsJson) as {reading:{finished:number;backfilledFinished:number;events:Array<{completionKind?:string}>}};expect(facts.reading.finished).toBe(0);expect(facts.reading.backfilledFinished).toBe(1);expect(facts.reading.events.at(-1)?.completionKind).toBe("backfill");data.readingEvents.splice(1,0,{...added,id:"started",type:"started",occurredAt:"2026-08-20T00:00:00Z",localDate:"2026-08-20"});const lifecycleFacts=JSON.parse((await buildWeeklySnapshot(data,"2026-08-24")).factsJson) as typeof facts;expect(lifecycleFacts.reading.finished).toBe(1);expect(lifecycleFacts.reading.backfilledFinished).toBe(0)});
});
