import {describe,expect,it} from "vitest";
import {migrateLegacyStore} from "./legacy";

const now="2026-08-24T00:00:00.000Z";
describe("legacy migration",()=>{
  it.each([["todo","open"],["doing","open"],["deferred","open"],["someday","open"],["done","done"],["dropped","dropped"]])("maps %s to %s",async(status,expected)=>{const result=await migrateLegacyStore({tasks:[{id:"t",title:"x",status,domain:"writing",createdAt:now,updatedAt:now}]},{timezone:"Asia/Shanghai",now});expect(result.data.tasks[0]).toMatchObject({status:expected,domain:"creation",contextPoints:[]})});
  it("converts dated deferrals without changing task status",async()=>{const result=await migrateLegacyStore({tasks:[{id:"t",title:"x",status:"deferred",domain:"work",plannedDate:"2026-08-27",createdAt:now,updatedAt:now}],events:[{id:"e",taskId:"t",type:"deferred",occurredAt:"2026-08-23T16:30:00.000Z",fromDate:"2026-08-24",toDate:"2026-08-27"}]},{timezone:"Asia/Shanghai",now});expect(result.data.tasks[0].status).toBe("open");expect(result.data.taskEvents[0]).toMatchObject({type:"rescheduled",localDate:"2026-08-24",timezone:"Asia/Shanghai"})});
  it("backs up but does not activate old AI or subjective text",async()=>{const legacy={tasks:[],events:[],dailyNotes:{"2026-08-20":"旧留痕"},reviews:[{userReflection:"旧反思",aiSummary:"人工改过"}],ai:{profile:{content:"旧画像"},weeklyDigests:[{content:"旧总结"}]}};const result=await migrateLegacyStore(legacy,{timezone:"Asia/Shanghai",now});expect(result.backup.store).toEqual(legacy);expect(result.data.aiReviews).toEqual([]);expect(result.data.profileSnapshots).toEqual([]);expect(JSON.stringify(result.data)).not.toContain("旧反思");expect(result.backup.checksum).toMatch(/^[a-f0-9]{64}$/)});
  it("keeps the backup checksum stable when a failed migration is retried",async()=>{const legacy={tasks:[{id:"t",title:"x",status:"todo",domain:"work"}]};const first=await migrateLegacyStore(legacy,{timezone:"Asia/Shanghai",now:"2026-08-24T00:00:00Z"});const retry=await migrateLegacyStore(legacy,{timezone:"Asia/Shanghai",now:"2026-08-24T00:05:00Z"});expect(retry.backup.checksum).toBe(first.backup.checksum)});
  it("keeps only one legacy focus for a date",async()=>{const tasks=[{id:"old",title:"old",status:"todo",domain:"work",plannedDate:"2026-08-24",isFocus:true,createdAt:now,updatedAt:"2026-08-24T01:00:00Z"},{id:"new",title:"new",status:"todo",domain:"work",plannedDate:"2026-08-24",isFocus:true,createdAt:now,updatedAt:"2026-08-24T02:00:00Z"}];const result=await migrateLegacyStore({tasks},{timezone:"Asia/Shanghai",now});expect(result.data.dailyFocus).toEqual([{date:"2026-08-24",taskId:"new",assignedAt:"2026-08-24T02:00:00Z"}])});
});
