import type { ThemeDefinition } from "../contracts";
import { GRAPHITE_AMBER_ASSETS } from "./assets";
import { GRAPHITE_AMBER_ICONS } from "./icons";

const tokens = {
  "--oe-bg": "#e9e8e3",
  "--oe-bg-deep": "#dcdad2",
  "--oe-surface": "#fbfaf6",
  "--oe-surface-muted": "#efede6",
  "--oe-surface-raised": "#ffffff",
  "--oe-text": "#252522",
  "--oe-text-strong": "#1f2a25",
  "--oe-text-muted": "#6c6a63",
  "--oe-text-faint": "#99968e",
  "--oe-primary": "#59605c",
  "--oe-primary-hover": "#3f4541",
  "--oe-primary-soft": "#e0e3e1",
  "--oe-accent": "#c38b3e",
  "--oe-accent-soft": "#f0e1c9",
  "--oe-danger": "#9b5c52",
  "--oe-border": "rgba(54,54,48,.12)",
  "--oe-border-strong": "rgba(54,54,48,.22)",
  "--oe-shadow": "0 22px 64px rgba(44,44,38,.11)",
  "--oe-shadow-soft": "0 10px 28px rgba(44,44,38,.075)",
  "--oe-radius-xs": "7px",
  "--oe-radius-sm": "10px",
  "--oe-radius-md": "14px",
  "--oe-radius-lg": "18px",
  "--oe-radius-xl": "22px",
  "--oe-font-ui": '"Inter", "Noto Sans SC", "Noto Sans CJK SC", "Source Han Sans SC", "PingFang SC", "Microsoft YaHei", "Segoe UI", system-ui, sans-serif',
  "--oe-font-display": '"Noto Serif SC", "Noto Serif CJK SC", "Source Han Serif SC", "Songti SC", "STSong", "SimSun", Georgia, serif',
  "--oe-font-mono": '"Cascadia Code", "SFMono-Regular", Consolas, monospace',
  "--oe-motion-fast": ".18s",
  "--oe-motion-normal": ".26s",
  "--oe-motion-slow": ".5s",
  "--oe-motion-micro": ".14s",
  "--oe-motion-ui": ".2s",
  "--oe-motion-layout": ".24s",
  "--oe-ease-standard": "ease",
  "--oe-ease-emphasized": "cubic-bezier(.2,.8,.2,1)",
  "--oe-main-window-canvas": "#f4f2ed",
  "--oe-page-canvas": "transparent",
  "--oe-page-lead-gap": "16px",
  "--oe-page-scroll-fade-height": "20px",
  "--oe-focus-surface": "linear-gradient(135deg, rgba(255,250,241,.94), rgba(246,238,224,.84))",
  "--oe-focus-surface-done": "linear-gradient(135deg, rgba(234,238,229,.94), rgba(247,241,228,.86))",
  "--oe-focus-border": "color-mix(in srgb, #c38b3e 16%, rgba(54,54,48,.12))",
  "--oe-titlebar-visual-height": "28px",
  "--oe-titlebar-hit-height": "34px",
  "--oe-todo-window-surface": "rgba(246,243,236,.95)",
  "--oe-todo-window-backdrop": "blur(24px) saturate(120%)",
  "--oe-spark-window-surface": "#f4f1eb",
  "--oe-spark-window-backdrop": "none",
};

export const graphiteAmberTheme: ThemeDefinition = {
  manifest: {
    id: "graphite-amber",
    name: "Graphite Amber",
    version: "1.0.0",
    apiVersion: 1,
    kind: "official",
    compatibleEditions: ["classic"],
    tokens,
    icons: GRAPHITE_AMBER_ICONS,
    assets: GRAPHITE_AMBER_ASSETS,
  },
  icons: GRAPHITE_AMBER_ICONS,
  assets: GRAPHITE_AMBER_ASSETS,
};
