import {describe,expect,it} from "vitest";
import {createEmptyStore} from "@/lib/storage/migrate";
import {buildProfileEvidencePack,buildWeekDigests,canonicalEvidence,evidenceIn,evidenceThrough,reconcileWeekDigests} from "./evidence";

describe("AI evidence boundary",()=>{const store=createEmptyStore();store.tasks=[{id:"technical-id",title:"完成项目",status:"done",domain:"work",contextPoints:[],plannedDate:"2026-08-03",createdAt:"2026-08-03T08:00:00Z",updatedAt:"2026-08-03T09:00:00Z"},{id:"future",title:"未来任务",status:"open",domain:"life",contextPoints:[],plannedDate:"2026-08-12",createdAt:"2026-08-12T08:00:00Z",updatedAt:"2026-08-12T08:00:00Z"}];store.appSettings["legacy.subjective"]="不得进入证据";
  it("uses factual entities but excludes ids, settings and legacy subjective text",()=>{const text=canonicalEvidence(store).map(value=>value.text).join("\n");expect(text).toContain("完成项目");expect(text).not.toContain("technical-id");expect(text).not.toContain("不得进入证据")});
  it("prevents future facts from entering a historical period",()=>{const evidence=canonicalEvidence(store);expect(evidenceThrough(evidence,"2026-08-09").some(value=>value.text.includes("未来任务"))).toBe(false);expect(evidenceIn(evidence,"2026-08-03","2026-08-09")).toHaveLength(1)});
  it("groups and reconciles factual digests",()=>{const original=buildWeekDigests(canonicalEvidence(store));const changed=buildWeekDigests([...canonicalEvidence(store),{date:"2026-08-04",kind:"task",text:"新增事实"}]);const reconciled=reconcileWeekDigests(changed,original);expect(original.map(value=>value.weekStart)).toEqual(["2026-08-03","2026-08-10"]);expect(reconciled[1]).toBe(original[1]);expect(reconciled[0]).not.toBe(original[0])});
  it("uses the focus day's completion event instead of current task status",()=>{const data=createEmptyStore();data.tasks=[{id:"focus",title:"当天未完成",status:"done",domain:"life",contextPoints:[],createdAt:"2026-08-01T00:00:00Z",updatedAt:"2026-08-10T00:00:00Z"}];data.dailyFocus=[{date:"2026-08-01",taskId:"focus",assignedAt:"2026-08-01T00:00:00Z"}];expect(canonicalEvidence(data).find(item=>item.kind==="daily_focus")?.text).toContain("当日完成：否");data.taskEvents=[{id:"done-later",taskId:"focus",type:"completed",occurredAt:"2026-08-10T00:00:00Z",localDate:"2026-08-10",timezone:"Asia/Shanghai"}];expect(canonicalEvidence(data).find(item=>item.kind==="daily_focus")?.text).toContain("当日完成：否")});
  it("builds a deterministic profile evidence pack without raw spark content",()=>{const data=createEmptyStore();data.tasks=[{id:"t",title:"完成一件事",status:"done",domain:"project",contextPoints:[],createdAt:"2026-08-01T00:00:00Z",updatedAt:"2026-08-02T00:00:00Z"}];data.taskEvents=[{id:"e",taskId:"t",type:"completed",occurredAt:"2026-08-02T00:00:00Z",localDate:"2026-08-02",timezone:"Asia/Shanghai"}];data.sparks=[{id:"s",content:"不应进入画像",status:"inbox",createdAt:"2026-08-02T00:00:00Z"}];const pack=buildProfileEvidencePack(data,"2026-08-24");expect(pack.windows.allTime.tasks.completed).toBe(1);expect(pack.representative.completedTasks).toEqual(["完成一件事"]);expect(JSON.stringify(pack)).not.toContain("不应进入画像");expect(buildProfileEvidencePack(data,"2026-08-24")).toEqual(pack)});
  it("cuts current entities and representative facts off at evidenceEnd",()=>{const data=createEmptyStore();data.tasks=[{id:"old",title:"边界前任务",status:"done",domain:"work",contextPoints:[],createdAt:"2026-07-01T00:00:00Z",updatedAt:"2026-08-20T00:00:00Z",completedAt:"2026-08-20T00:00:00Z"},{id:"future",title:"边界后任务",status:"open",domain:"life",contextPoints:[],createdAt:"2026-08-20T00:00:00Z",updatedAt:"2026-08-20T00:00:00Z"}];data.taskEvents=[{id:"done",taskId:"old",type:"completed",occurredAt:"2026-08-20T00:00:00Z",localDate:"2026-08-20",timezone:"Asia/Shanghai"}];data.readingItems=[{id:"book",title:"边界后读完",type:"book",status:"finished",createdAt:"2026-08-20T00:00:00Z",updatedAt:"2026-08-20T00:00:00Z"}];data.readingEvents=[{id:"read",readingItemId:"book",type:"finished",occurredAt:"2026-08-20T00:00:00Z",localDate:"2026-08-20",timezone:"Asia/Shanghai"}];const pack=buildProfileEvidencePack(data,"2026-08-10");expect(pack.windows.allTime.tasks.completed).toBe(0);expect(pack.openTaskAge.map(item=>item.title)).toEqual(["边界前任务"]);expect(pack.representative.completedTasks).toEqual([]);expect(pack.representative.reading).toEqual([])});
});
